/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication2;

import java.io.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author c0628439
 */
public class NewJFrame extends javax.swing.JFrame{
int credits = 100;
    private Clip SoundClip;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        game.setVisible(false);
        menu.setVisible(true);
        Rules.setVisible(false);
        Credits.setText(Integer.toString(credits));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Rules = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        game = new javax.swing.JPanel();
        topayout = new javax.swing.JButton();
        Credits = new javax.swing.JLabel();
        MenuBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        window1 = new javax.swing.JPanel();
        win1 = new javax.swing.JLabel();
        window2 = new javax.swing.JPanel();
        win2 = new javax.swing.JLabel();
        window3 = new javax.swing.JPanel();
        win3 = new javax.swing.JLabel();
        info = new javax.swing.JTextField();
        Spin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        menu.setPreferredSize(new java.awt.Dimension(480, 570));
        menu.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Flan.gif"))); // NOI18N
        menu.add(jLabel11);
        jLabel11.setBounds(210, 340, 120, 110);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Remi.gif"))); // NOI18N
        menu.add(jLabel9);
        jLabel9.setBounds(90, 330, 130, 110);

        jButton2.setText("Enable/disable sound");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menu.add(jButton2);
        jButton2.setBounds(10, 540, 210, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Sakuya.gif"))); // NOI18N
        menu.add(jLabel10);
        jLabel10.setBounds(360, 220, 70, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/patchouli.gif"))); // NOI18N
        menu.add(jLabel8);
        jLabel8.setBounds(220, 200, 100, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Meiling-Tiger.gif"))); // NOI18N
        menu.add(jLabel7);
        jLabel7.setBounds(150, 220, 70, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Cirno.gif"))); // NOI18N
        menu.add(jLabel4);
        jLabel4.setBounds(40, 220, 80, 90);

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menu.add(jButton1);
        jButton1.setBounds(140, 440, 189, 88);

        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menu.add(jButton3);
        jButton3.setBounds(380, 480, 53, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Scarlet Devil Slots");
        menu.add(jLabel3);
        jLabel3.setBounds(90, 80, 290, 44);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/rsz_scarletdevilmansionfull1189284.jpg"))); // NOI18N
        menu.add(jLabel6);
        jLabel6.setBounds(0, 0, 480, 570);

        Rules.setBackground(new java.awt.Color(255, 255, 255));
        Rules.setForeground(new java.awt.Color(255, 255, 255));
        Rules.setPreferredSize(new java.awt.Dimension(480, 600));
        Rules.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Flan.gif"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(280, 70, 130, 90);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/patchouli.gif"))); // NOI18N
        jLabel24.setText("jLabel19");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(300, 360, 90, 130);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("3 X");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(270, 410, 60, 70);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Cirno.gif"))); // NOI18N
        jLabel20.setText("jLabel19");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(70, 410, 80, 70);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("= 1000");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(400, 80, 110, 70);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Cirno.gif"))); // NOI18N
        jLabel21.setText("jLabel19");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(60, 300, 80, 70);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("2 X");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 300, 60, 70);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("3 X");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 210, 60, 70);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Cirno.gif"))); // NOI18N
        jLabel22.setText("jLabel19");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(60, 210, 80, 70);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("3 X");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 110, 60, 70);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Meiling-Tiger.gif"))); // NOI18N
        jLabel23.setText("jLabel19");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(70, 90, 70, 100);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("3 X");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(260, 110, 60, 70);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("3 X");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(260, 190, 60, 70);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("3 X");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(260, 300, 60, 70);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Sakuya.gif"))); // NOI18N
        jLabel31.setText("jLabel19");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(330, 260, 60, 120);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Remi.gif"))); // NOI18N
        jLabel32.setText("jLabel19");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(290, 160, 110, 100);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("1 X");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 410, 60, 70);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("= 5");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(160, 410, 60, 70);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("= 10");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(150, 300, 80, 70);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("= 15");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(150, 210, 80, 70);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("= 30");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(150, 110, 80, 70);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("= 60");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(390, 410, 80, 70);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("= 120");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(390, 300, 100, 70);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("= 300");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(400, 190, 100, 70);

        jButton4.setText("back to game");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(170, 20, 110, 40);

        Rules.add(jPanel1);
        jPanel1.setBounds(0, 70, 480, 500);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PAYOUTS");
        Rules.add(jLabel12);
        jLabel12.setBounds(100, 0, 290, 70);

        game.setBackground(new java.awt.Color(51, 51, 51));
        game.setPreferredSize(new java.awt.Dimension(480, 600));
        game.setLayout(null);

        topayout.setText("Payouts");
        topayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topayoutActionPerformed(evt);
            }
        });
        game.add(topayout);
        topayout.setBounds(30, 370, 130, 23);

        Credits.setForeground(new java.awt.Color(255, 255, 255));
        game.add(Credits);
        Credits.setBounds(240, 440, 50, 20);

        MenuBtn.setText("Quit to Main Menu");
        MenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnActionPerformed(evt);
            }
        });
        game.add(MenuBtn);
        MenuBtn.setBounds(330, 370, 130, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Credits");
        game.add(jLabel1);
        jLabel1.setBounds(180, 440, 50, 20);

        window1.setBackground(new java.awt.Color(153, 153, 153));
        window1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout window1Layout = new javax.swing.GroupLayout(window1);
        window1.setLayout(window1Layout);
        window1Layout.setHorizontalGroup(
            window1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(win1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        window1Layout.setVerticalGroup(
            window1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, window1Layout.createSequentialGroup()
                .addComponent(win1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        game.add(window1);
        window1.setBounds(10, 110, 140, 140);

        window2.setBackground(new java.awt.Color(153, 153, 153));
        window2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout window2Layout = new javax.swing.GroupLayout(window2);
        window2.setLayout(window2Layout);
        window2Layout.setHorizontalGroup(
            window2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(win2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        window2Layout.setVerticalGroup(
            window2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(win2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        game.add(window2);
        window2.setBounds(170, 110, 140, 140);

        window3.setBackground(new java.awt.Color(153, 153, 153));
        window3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout window3Layout = new javax.swing.GroupLayout(window3);
        window3.setLayout(window3Layout);
        window3Layout.setHorizontalGroup(
            window3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(win3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        window3Layout.setVerticalGroup(
            window3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(win3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        game.add(window3);
        window3.setBounds(330, 110, 140, 140);

        info.setEditable(false);
        info.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        info.setText("The Maidens are waiting warmly");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        game.add(info);
        info.setBounds(40, 510, 400, 30);

        Spin.setText("Spin");
        Spin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpinActionPerformed(evt);
            }
        });
        game.add(Spin);
        Spin.setBounds(180, 350, 130, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/rsz_scarletdevilmansionfull1222554.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(480, 570));
        game.add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 570);

        jLabel5.setPreferredSize(new java.awt.Dimension(480, 570));
        game.add(jLabel5);
        jLabel5.setBounds(0, 0, 480, 551);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Rules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Rules, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void SpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpinActionPerformed

        Random rand = new Random();
        
        int srn1 = rand.nextInt(19) + 1;
        int srn2 = rand.nextInt(19) + 1;
        int srn3 = rand.nextInt(19) + 1;
        //window 1 images
        if (srn1 == 1 ){
            win1.setIcon(new javax.swing.ImageIcon("Flan.gif"));
        }
        if (srn1 == 2 | srn1 == 3 | srn1 == 4 | srn1 == 5 ){
            win1.setIcon(new javax.swing.ImageIcon("patchouli.gif"));
        }
        if (srn1 == 6 | srn1 == 7 | srn1 == 8){
            win1.setIcon(new javax.swing.ImageIcon("Sakuya.gif"));
        }
        if (srn1 == 9 | srn1 == 10  ){
            win1.setIcon(new javax.swing.ImageIcon("Remi.gif"));
        }
        if (srn1 == 11 | srn1 ==12 | srn1 ==13 | srn1 ==14 | srn1 == 15 ){
            win1.setIcon(new javax.swing.ImageIcon("Cirno.gif"));
        }
        if (srn1 == 16 | srn1 ==17 | srn1 ==18 | srn1 == 19){
            win1.setIcon(new javax.swing.ImageIcon("Meiling-Tiger.gif"));
        }
        // window 2 images----------------------------------------------------------
       if (srn2 == 1 ){
            win2.setIcon(new javax.swing.ImageIcon("Flan.gif"));
        }
        if (srn2 == 2 | srn2 == 3 | srn2 == 4 | srn2 == 5 ){
            win2.setIcon(new javax.swing.ImageIcon("patchouli.gif"));
        }
        if (srn2 == 6 | srn2 == 7 | srn2 == 8){
            win2.setIcon(new javax.swing.ImageIcon("Sakuya.gif"));
        }
        if (srn2 == 9 | srn2 == 10  ){
            win2.setIcon(new javax.swing.ImageIcon("Remi.gif"));
        }
        if (srn2 == 11 | srn2 ==12 | srn2 ==13 | srn2 ==14 | srn2 == 15 ){
            win2.setIcon(new javax.swing.ImageIcon("Cirno.gif"));
        }
        if (srn2 == 16 | srn2 ==17 | srn2 ==18 | srn2 == 19){
            win2.setIcon(new javax.swing.ImageIcon("Meiling-Tiger.gif"));
        }
        // window 3 images
        if (srn2 == 1 ){
            win3.setIcon(new javax.swing.ImageIcon("Flan.gif"));
        }
        if (srn3 == 2 | srn3 == 3 | srn3 == 4 | srn3 == 5 ){
            win3.setIcon(new javax.swing.ImageIcon("patchouli.gif"));
        }
        if (srn3 == 6 |srn3 == 7 | srn3 == 8){
            win3.setIcon(new javax.swing.ImageIcon("Sakuya.gif"));
        }
        if (srn3 == 9 | srn3 == 10  ){
            win3.setIcon(new javax.swing.ImageIcon("Remi.gif"));
        }
        if (srn3 == 11 | srn3 ==12 | srn3 ==13 | srn3 ==14 | srn3 == 15 ){
            win3.setIcon(new javax.swing.ImageIcon("Cirno.gif"));
        }
        if (srn3 == 16 | srn3 ==17 | srn3 ==18 | srn3 == 19){
            win3.setIcon(new javax.swing.ImageIcon("Meiling-Tiger.gif"));
        }
//If a  payout happens 
        //single cirno apears (blue fairy)
        if ((srn1>=11 && srn1<= 15) && (srn2<=10 || srn2>=16)&& (srn3<=10 || srn3>=16)){
         credits = credits + 5;
         Credits.setText(Integer.toString(credits));
          info.setText("One Cirno 5 credits earned");
        }
        else if ((srn1<=10 || srn1>=16) && (srn2>=11 && srn2<=15)&& (srn3<=10 || srn3>=16))
                 {
                      credits = credits + 5;
         Credits.setText(Integer.toString(credits));
          info.setText("One Cirno 5 credits earned");
        }
        else if ((srn1<=10 || srn1>=16) && (srn2<=10 || srn2>=16)&& (srn3>=11 && srn3<=15))
                 {
                     credits = credits + 5;
         Credits.setText(Integer.toString(credits));
         info.setText("One Cirno 5 credits earned");
                 }
// two cirnos apear
        if ((srn1>=11 && srn1<= 15) && (srn2>=11 && srn2<=15)&& (srn3<=10 || srn3>=16)){
            credits = credits + 10;
            Credits.setText(Integer.toString(credits));
             info.setText("YAY! two Cirno 10 credits earned");
            }
        else if ((srn1<=10 || srn1>=16) && (srn2>=11 && srn2<=15)&& (srn3>=11 && srn3<=15)){
            credits = credits + 10;
            Credits.setText(Integer.toString(credits));
             info.setText("YAY! two Cirno 10 credits earned");
            }
        else if ((srn1>=11 && srn1<= 15) && (srn2<=10 || srn2>=16)&& (srn3>=11 && srn3<=15)){
            credits = credits + 10;
            Credits.setText(Integer.toString(credits));
            info.setText("YAY! two Cirno 10 credits earned");
                 }
// Triple Cirno
        if ((srn1>=11 && srn1<= 15) && (srn2>=11 && srn2<= 15)&& (srn3>=11 && srn3<= 15)){
            credits = credits + 15;
            Credits.setText(Integer.toString(credits));
             info.setText("YOU ARE THE STRONGEST 15 CREDITS EARNED!!");
            }
// Meiling green outfit
 if ((srn1>=16 && srn1<= 19) && (srn2>=16 && srn2<= 19)&& (srn3>=16 && srn3<= 19)){
            credits = credits + 30;
            Credits.setText(Integer.toString(credits));
             info.setText("BEING ALEART AND ASLEEP IS A GREAT SKILL 30 Credits");
            }
 //Patchouli pink/purple
  if ((srn1>=2 && srn1<= 5) && (srn2>=2 && srn2<= 5)&& (srn3>=2 && srn3<= 5)){
            credits = credits + 60;
            Credits.setText(Integer.toString(credits));
             info.setText("ENTER VOILE THE MAGIC LIBRARY 60 Credits earned");
            }
// Sakuya (maid)
   if ((srn1>=6 && srn1<= 8) && (srn2>=6 && srn2<= 8)&& (srn3>=6 && srn3<= 8)){
            credits = credits +120;
            Credits.setText(Integer.toString(credits));
             info.setText("TIME IS SLOWING DOWN 120 Credits");
            }
// Remilia vampire
    if ((srn1>=9 && srn1<= 10) && (srn2>=9 && srn2<= 10)&& (srn3>=9 && srn3<= 10)){
            credits = credits + 300;
            Credits.setText(Integer.toString(credits));
             info.setText("SEPTETTET FOR THE FILLED BANK 300 credits!!");
            }
// Flandre gem wings
     if ((srn1==1) && (srn2==1)&& (srn3==1)){
            credits = credits + 1000;
            Credits.setText(Integer.toString(credits));
             info.setText("UN OWEN IS YOU, 1000 CREDITS EARNED!!!!");
            }
// spends credits if spun and restarts if you run out
    if (srn1<=19 && srn2<=19 && srn3<=19){
                 credits =credits - 5;
                 Credits.setText(Integer.toString(credits));
                 }
    if (credits==0){
             JFrame frame = new JFrame();
    String message = "You are out of money.... Quiting to main menu";
    int answer = JOptionPane.showConfirmDialog(frame, message,"Out of Credits D:",YES_OPTION);
    if (answer == JOptionPane.YES_OPTION) {
        credits = 100;
        info.setText("The Maidens are waiting warmly");
        game.setVisible(false);
menu.setVisible(true);
Credits.setText(Integer.toString(credits));
win1.setIcon(null);
win2.setIcon(null);
win3.setIcon(null);
    }
         }
    }//GEN-LAST:event_SpinActionPerformed

    private void MenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnActionPerformed
game.setVisible(false);
menu.setVisible(true);
credits = 100;
Credits.setText(Integer.toString(credits));
win1.setIcon(null);
win2.setIcon(null);
win3.setIcon(null);
info.setText("The Maidens are waiting warmly");
    }//GEN-LAST:event_MenuBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
game.setVisible(true);
menu.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 JFrame frame = new JFrame();
    String message = "Are you sure you want to leave";
    int answer = JOptionPane.showConfirmDialog(frame, message,"Do you want to quit?",YES_OPTION);
    if (answer == JOptionPane.YES_OPTION) {
        StopMusic();
        System.exit(0);
        
    } else if (answer == JOptionPane.NO_OPTION) {
     frame.dispose();
     
    }
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
    JFrame frame = new JFrame();
    String message = "Do you want music to play (yes to turn on, no to turn off or for not to start)";
    int answer = JOptionPane.showConfirmDialog(frame, message,"Music?",YES_OPTION);
    if (answer == JOptionPane.YES_OPTION) {
        try {
            PlayMe();
        } catch (UnsupportedAudioFileException | IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else if (answer == JOptionPane.NO_OPTION) {
     frame.dispose();
     StopMusic();
     
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     game.setVisible(true);
    Rules.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void topayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topayoutActionPerformed
         game.setVisible(false);
        Rules.setVisible(true);
    }//GEN-LAST:event_topayoutActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoActionPerformed
private void PlayMe() throws UnsupportedAudioFileException, IOException{	
		 	try {
		 		//read audio data from whatever source (file/classloader/etc.)
				InputStream audioSrc = getClass().getResourceAsStream("BGM.wav");
				//add buffer for mark/reset support
				InputStream bufferedIn = new BufferedInputStream(audioSrc);
				AudioInputStream AS1 = AudioSystem.getAudioInputStream(bufferedIn);
		 		
		 		AudioFormat AF = AS1.getFormat();
                                
                SoundClip = AudioSystem.getClip();
                DataLine.Info thing;
                             thing = new DataLine.Info(Clip.class, AF);

              
              try{
                    SoundClip.open(AS1);
                    SoundClip.loop(Clip.LOOP_CONTINUOUSLY);
                    SoundClip.start();
              }catch(IOException | LineUnavailableException e) {
		 		System.out.println("Error" + e);
		 	}
               
		}catch(IOException | LineUnavailableException e) {
		 		System.out.println("Error" + e);
}
}
private void StopMusic() {
		SoundClip.stop();
	}	

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Credits;
    public javax.swing.JButton MenuBtn;
    public javax.swing.JPanel Rules;
    public javax.swing.JButton Spin;
    public javax.swing.JPanel game;
    public javax.swing.JTextField info;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel menu;
    public javax.swing.JButton topayout;
    public javax.swing.JLabel win1;
    public javax.swing.JLabel win2;
    public javax.swing.JLabel win3;
    public javax.swing.JPanel window1;
    public javax.swing.JPanel window2;
    public javax.swing.JPanel window3;
    // End of variables declaration//GEN-END:variables
}
